version: '3.8'

services:
  togglr-reverse-proxy:
    build:
      context: ../reverse-proxy
      dockerfile: Dockerfile
    container_name: togglr-reverse-proxy
    ports:
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
      - BACKEND_URL=http://togglr-backend:8080
      - WS_BACKEND_URL=http://togglr-backend:8082
      - FRONTEND_URL=http://togglr-frontend
      - SSL_CERT=${SSL_CERT}
      - SSL_CERT_KEY=${SSL_CERT_KEY}
      - SECURE_LINK_MD5=${SECURE_LINK_MD5}
    volumes:
      - "./nginx/ssl:/etc/nginx/ssl"
    depends_on:
      togglr-frontend:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "netstat", "-tln", "|", "grep", "443 && netstat", "-tln", "|", "grep", "8090"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  togglr-frontend:
    build:
      context: ../webui
      dockerfile: Dockerfile
    container_name: togglr-frontend
    environment:
      - TOGGLR_API_BASE_URL=https://${DOMAIN}
      - TOGGLR_WS_BASE_URL=https://${DOMAIN}
    restart: always
    depends_on:
      togglr-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "--silent", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  togglr-backend:
    container_name: togglr-backend
    build:
      context: ../
      target: prod
      dockerfile: Dockerfile
    # ports:
    #   - "8080:8080"
    #   - "8081:8081"
    #   - "8082:8082"
    env_file:
      - compose.env
    command: ["/bin/app", "server"]
    depends_on:
      togglr-postgresql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "--silent", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  togglr-postgresql:
    image: timescale/timescaledb:latest-pg17
    container_name: togglr-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data/main
    volumes:
      - "postgresql_togglr:/var/lib/postgresql/data/main"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "PG_PASSWORD=password pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
volumes:
    postgresql_togglr: