// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontract

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProductInfoRepository creates a new instance of MockProductInfoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductInfoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductInfoRepository {
	mock := &MockProductInfoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductInfoRepository is an autogenerated mock type for the ProductInfoRepository type
type MockProductInfoRepository struct {
	mock.Mock
}

type MockProductInfoRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductInfoRepository) EXPECT() *MockProductInfoRepository_Expecter {
	return &MockProductInfoRepository_Expecter{mock: &_m.Mock}
}

// GetClientID provides a mock function for the type MockProductInfoRepository
func (_mock *MockProductInfoRepository) GetClientID(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetClientID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductInfoRepository_GetClientID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientID'
type MockProductInfoRepository_GetClientID_Call struct {
	*mock.Call
}

// GetClientID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProductInfoRepository_Expecter) GetClientID(ctx interface{}) *MockProductInfoRepository_GetClientID_Call {
	return &MockProductInfoRepository_GetClientID_Call{Call: _e.mock.On("GetClientID", ctx)}
}

func (_c *MockProductInfoRepository_GetClientID_Call) Run(run func(ctx context.Context)) *MockProductInfoRepository_GetClientID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProductInfoRepository_GetClientID_Call) Return(s string, err error) *MockProductInfoRepository_GetClientID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockProductInfoRepository_GetClientID_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockProductInfoRepository_GetClientID_Call {
	_c.Call.Return(run)
	return _c
}
