// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontract

import (
	"context"
	"encoding/json"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/togglr-project/togglr/internal/domain"
)

// NewMockUserNotificationsRepository creates a new instance of MockUserNotificationsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserNotificationsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserNotificationsRepository {
	mock := &MockUserNotificationsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserNotificationsRepository is an autogenerated mock type for the UserNotificationsRepository type
type MockUserNotificationsRepository struct {
	mock.Mock
}

type MockUserNotificationsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserNotificationsRepository) EXPECT() *MockUserNotificationsRepository_Expecter {
	return &MockUserNotificationsRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserNotificationsRepository
func (_mock *MockUserNotificationsRepository) Create(ctx context.Context, userID domain.UserID, notificationType domain.UserNotificationType, content json.RawMessage) (domain.UserNotification, error) {
	ret := _mock.Called(ctx, userID, notificationType, content)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.UserNotification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, domain.UserNotificationType, json.RawMessage) (domain.UserNotification, error)); ok {
		return returnFunc(ctx, userID, notificationType, content)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, domain.UserNotificationType, json.RawMessage) domain.UserNotification); ok {
		r0 = returnFunc(ctx, userID, notificationType, content)
	} else {
		r0 = ret.Get(0).(domain.UserNotification)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, domain.UserNotificationType, json.RawMessage) error); ok {
		r1 = returnFunc(ctx, userID, notificationType, content)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserNotificationsRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserNotificationsRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - notificationType domain.UserNotificationType
//   - content json.RawMessage
func (_e *MockUserNotificationsRepository_Expecter) Create(ctx interface{}, userID interface{}, notificationType interface{}, content interface{}) *MockUserNotificationsRepository_Create_Call {
	return &MockUserNotificationsRepository_Create_Call{Call: _e.mock.On("Create", ctx, userID, notificationType, content)}
}

func (_c *MockUserNotificationsRepository_Create_Call) Run(run func(ctx context.Context, userID domain.UserID, notificationType domain.UserNotificationType, content json.RawMessage)) *MockUserNotificationsRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 domain.UserNotificationType
		if args[2] != nil {
			arg2 = args[2].(domain.UserNotificationType)
		}
		var arg3 json.RawMessage
		if args[3] != nil {
			arg3 = args[3].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserNotificationsRepository_Create_Call) Return(userNotification domain.UserNotification, err error) *MockUserNotificationsRepository_Create_Call {
	_c.Call.Return(userNotification, err)
	return _c
}

func (_c *MockUserNotificationsRepository_Create_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, notificationType domain.UserNotificationType, content json.RawMessage) (domain.UserNotification, error)) *MockUserNotificationsRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOld provides a mock function for the type MockUserNotificationsRepository
func (_mock *MockUserNotificationsRepository) DeleteOld(ctx context.Context, maxAge time.Duration, limit uint) (uint, error) {
	ret := _mock.Called(ctx, maxAge, limit)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOld")
	}

	var r0 uint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, uint) (uint, error)); ok {
		return returnFunc(ctx, maxAge, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, uint) uint); ok {
		r0 = returnFunc(ctx, maxAge, limit)
	} else {
		r0 = ret.Get(0).(uint)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration, uint) error); ok {
		r1 = returnFunc(ctx, maxAge, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserNotificationsRepository_DeleteOld_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOld'
type MockUserNotificationsRepository_DeleteOld_Call struct {
	*mock.Call
}

// DeleteOld is a helper method to define mock.On call
//   - ctx context.Context
//   - maxAge time.Duration
//   - limit uint
func (_e *MockUserNotificationsRepository_Expecter) DeleteOld(ctx interface{}, maxAge interface{}, limit interface{}) *MockUserNotificationsRepository_DeleteOld_Call {
	return &MockUserNotificationsRepository_DeleteOld_Call{Call: _e.mock.On("DeleteOld", ctx, maxAge, limit)}
}

func (_c *MockUserNotificationsRepository_DeleteOld_Call) Run(run func(ctx context.Context, maxAge time.Duration, limit uint)) *MockUserNotificationsRepository_DeleteOld_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserNotificationsRepository_DeleteOld_Call) Return(v uint, err error) *MockUserNotificationsRepository_DeleteOld_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockUserNotificationsRepository_DeleteOld_Call) RunAndReturn(run func(ctx context.Context, maxAge time.Duration, limit uint) (uint, error)) *MockUserNotificationsRepository_DeleteOld_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockUserNotificationsRepository
func (_mock *MockUserNotificationsRepository) GetByID(ctx context.Context, id domain.UserNotificationID) (domain.UserNotification, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.UserNotification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserNotificationID) (domain.UserNotification, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserNotificationID) domain.UserNotification); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.UserNotification)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserNotificationID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserNotificationsRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserNotificationsRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.UserNotificationID
func (_e *MockUserNotificationsRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockUserNotificationsRepository_GetByID_Call {
	return &MockUserNotificationsRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserNotificationsRepository_GetByID_Call) Run(run func(ctx context.Context, id domain.UserNotificationID)) *MockUserNotificationsRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserNotificationID
		if args[1] != nil {
			arg1 = args[1].(domain.UserNotificationID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserNotificationsRepository_GetByID_Call) Return(userNotification domain.UserNotification, err error) *MockUserNotificationsRepository_GetByID_Call {
	_c.Call.Return(userNotification, err)
	return _c
}

func (_c *MockUserNotificationsRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id domain.UserNotificationID) (domain.UserNotification, error)) *MockUserNotificationsRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type MockUserNotificationsRepository
func (_mock *MockUserNotificationsRepository) GetByUserID(ctx context.Context, userID domain.UserID, limit uint, offset uint) ([]domain.UserNotification, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []domain.UserNotification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, uint, uint) ([]domain.UserNotification, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, uint, uint) []domain.UserNotification); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserNotification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, uint, uint) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserNotificationsRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockUserNotificationsRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - limit uint
//   - offset uint
func (_e *MockUserNotificationsRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockUserNotificationsRepository_GetByUserID_Call {
	return &MockUserNotificationsRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID, limit, offset)}
}

func (_c *MockUserNotificationsRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID domain.UserID, limit uint, offset uint)) *MockUserNotificationsRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 uint
		if args[3] != nil {
			arg3 = args[3].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserNotificationsRepository_GetByUserID_Call) Return(userNotifications []domain.UserNotification, err error) *MockUserNotificationsRepository_GetByUserID_Call {
	_c.Call.Return(userNotifications, err)
	return _c
}

func (_c *MockUserNotificationsRepository_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, limit uint, offset uint) ([]domain.UserNotification, error)) *MockUserNotificationsRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingEmailNotifications provides a mock function for the type MockUserNotificationsRepository
func (_mock *MockUserNotificationsRepository) GetPendingEmailNotifications(ctx context.Context, limit uint) ([]domain.UserNotification, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingEmailNotifications")
	}

	var r0 []domain.UserNotification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]domain.UserNotification, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []domain.UserNotification); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserNotification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserNotificationsRepository_GetPendingEmailNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingEmailNotifications'
type MockUserNotificationsRepository_GetPendingEmailNotifications_Call struct {
	*mock.Call
}

// GetPendingEmailNotifications is a helper method to define mock.On call
//   - ctx context.Context
//   - limit uint
func (_e *MockUserNotificationsRepository_Expecter) GetPendingEmailNotifications(ctx interface{}, limit interface{}) *MockUserNotificationsRepository_GetPendingEmailNotifications_Call {
	return &MockUserNotificationsRepository_GetPendingEmailNotifications_Call{Call: _e.mock.On("GetPendingEmailNotifications", ctx, limit)}
}

func (_c *MockUserNotificationsRepository_GetPendingEmailNotifications_Call) Run(run func(ctx context.Context, limit uint)) *MockUserNotificationsRepository_GetPendingEmailNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserNotificationsRepository_GetPendingEmailNotifications_Call) Return(userNotifications []domain.UserNotification, err error) *MockUserNotificationsRepository_GetPendingEmailNotifications_Call {
	_c.Call.Return(userNotifications, err)
	return _c
}

func (_c *MockUserNotificationsRepository_GetPendingEmailNotifications_Call) RunAndReturn(run func(ctx context.Context, limit uint) ([]domain.UserNotification, error)) *MockUserNotificationsRepository_GetPendingEmailNotifications_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingEmailNotificationsForUpdate provides a mock function for the type MockUserNotificationsRepository
func (_mock *MockUserNotificationsRepository) GetPendingEmailNotificationsForUpdate(ctx context.Context, limit uint) ([]domain.UserNotification, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingEmailNotificationsForUpdate")
	}

	var r0 []domain.UserNotification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]domain.UserNotification, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []domain.UserNotification); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserNotification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserNotificationsRepository_GetPendingEmailNotificationsForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingEmailNotificationsForUpdate'
type MockUserNotificationsRepository_GetPendingEmailNotificationsForUpdate_Call struct {
	*mock.Call
}

// GetPendingEmailNotificationsForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - limit uint
func (_e *MockUserNotificationsRepository_Expecter) GetPendingEmailNotificationsForUpdate(ctx interface{}, limit interface{}) *MockUserNotificationsRepository_GetPendingEmailNotificationsForUpdate_Call {
	return &MockUserNotificationsRepository_GetPendingEmailNotificationsForUpdate_Call{Call: _e.mock.On("GetPendingEmailNotificationsForUpdate", ctx, limit)}
}

func (_c *MockUserNotificationsRepository_GetPendingEmailNotificationsForUpdate_Call) Run(run func(ctx context.Context, limit uint)) *MockUserNotificationsRepository_GetPendingEmailNotificationsForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserNotificationsRepository_GetPendingEmailNotificationsForUpdate_Call) Return(userNotifications []domain.UserNotification, err error) *MockUserNotificationsRepository_GetPendingEmailNotificationsForUpdate_Call {
	_c.Call.Return(userNotifications, err)
	return _c
}

func (_c *MockUserNotificationsRepository_GetPendingEmailNotificationsForUpdate_Call) RunAndReturn(run func(ctx context.Context, limit uint) ([]domain.UserNotification, error)) *MockUserNotificationsRepository_GetPendingEmailNotificationsForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnreadCount provides a mock function for the type MockUserNotificationsRepository
func (_mock *MockUserNotificationsRepository) GetUnreadCount(ctx context.Context, userID domain.UserID) (uint, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUnreadCount")
	}

	var r0 uint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) (uint, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) uint); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(uint)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserNotificationsRepository_GetUnreadCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnreadCount'
type MockUserNotificationsRepository_GetUnreadCount_Call struct {
	*mock.Call
}

// GetUnreadCount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
func (_e *MockUserNotificationsRepository_Expecter) GetUnreadCount(ctx interface{}, userID interface{}) *MockUserNotificationsRepository_GetUnreadCount_Call {
	return &MockUserNotificationsRepository_GetUnreadCount_Call{Call: _e.mock.On("GetUnreadCount", ctx, userID)}
}

func (_c *MockUserNotificationsRepository_GetUnreadCount_Call) Run(run func(ctx context.Context, userID domain.UserID)) *MockUserNotificationsRepository_GetUnreadCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserNotificationsRepository_GetUnreadCount_Call) Return(v uint, err error) *MockUserNotificationsRepository_GetUnreadCount_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockUserNotificationsRepository_GetUnreadCount_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID) (uint, error)) *MockUserNotificationsRepository_GetUnreadCount_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllAsRead provides a mock function for the type MockUserNotificationsRepository
func (_mock *MockUserNotificationsRepository) MarkAllAsRead(ctx context.Context, userID domain.UserID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllAsRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserNotificationsRepository_MarkAllAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllAsRead'
type MockUserNotificationsRepository_MarkAllAsRead_Call struct {
	*mock.Call
}

// MarkAllAsRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
func (_e *MockUserNotificationsRepository_Expecter) MarkAllAsRead(ctx interface{}, userID interface{}) *MockUserNotificationsRepository_MarkAllAsRead_Call {
	return &MockUserNotificationsRepository_MarkAllAsRead_Call{Call: _e.mock.On("MarkAllAsRead", ctx, userID)}
}

func (_c *MockUserNotificationsRepository_MarkAllAsRead_Call) Run(run func(ctx context.Context, userID domain.UserID)) *MockUserNotificationsRepository_MarkAllAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserNotificationsRepository_MarkAllAsRead_Call) Return(err error) *MockUserNotificationsRepository_MarkAllAsRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserNotificationsRepository_MarkAllAsRead_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID) error) *MockUserNotificationsRepository_MarkAllAsRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAsRead provides a mock function for the type MockUserNotificationsRepository
func (_mock *MockUserNotificationsRepository) MarkAsRead(ctx context.Context, id domain.UserNotificationID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserNotificationID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserNotificationsRepository_MarkAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAsRead'
type MockUserNotificationsRepository_MarkAsRead_Call struct {
	*mock.Call
}

// MarkAsRead is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.UserNotificationID
func (_e *MockUserNotificationsRepository_Expecter) MarkAsRead(ctx interface{}, id interface{}) *MockUserNotificationsRepository_MarkAsRead_Call {
	return &MockUserNotificationsRepository_MarkAsRead_Call{Call: _e.mock.On("MarkAsRead", ctx, id)}
}

func (_c *MockUserNotificationsRepository_MarkAsRead_Call) Run(run func(ctx context.Context, id domain.UserNotificationID)) *MockUserNotificationsRepository_MarkAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserNotificationID
		if args[1] != nil {
			arg1 = args[1].(domain.UserNotificationID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserNotificationsRepository_MarkAsRead_Call) Return(err error) *MockUserNotificationsRepository_MarkAsRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserNotificationsRepository_MarkAsRead_Call) RunAndReturn(run func(ctx context.Context, id domain.UserNotificationID) error) *MockUserNotificationsRepository_MarkAsRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkEmailAsFailed provides a mock function for the type MockUserNotificationsRepository
func (_mock *MockUserNotificationsRepository) MarkEmailAsFailed(ctx context.Context, id domain.UserNotificationID, reason string) error {
	ret := _mock.Called(ctx, id, reason)

	if len(ret) == 0 {
		panic("no return value specified for MarkEmailAsFailed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserNotificationID, string) error); ok {
		r0 = returnFunc(ctx, id, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserNotificationsRepository_MarkEmailAsFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkEmailAsFailed'
type MockUserNotificationsRepository_MarkEmailAsFailed_Call struct {
	*mock.Call
}

// MarkEmailAsFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.UserNotificationID
//   - reason string
func (_e *MockUserNotificationsRepository_Expecter) MarkEmailAsFailed(ctx interface{}, id interface{}, reason interface{}) *MockUserNotificationsRepository_MarkEmailAsFailed_Call {
	return &MockUserNotificationsRepository_MarkEmailAsFailed_Call{Call: _e.mock.On("MarkEmailAsFailed", ctx, id, reason)}
}

func (_c *MockUserNotificationsRepository_MarkEmailAsFailed_Call) Run(run func(ctx context.Context, id domain.UserNotificationID, reason string)) *MockUserNotificationsRepository_MarkEmailAsFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserNotificationID
		if args[1] != nil {
			arg1 = args[1].(domain.UserNotificationID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserNotificationsRepository_MarkEmailAsFailed_Call) Return(err error) *MockUserNotificationsRepository_MarkEmailAsFailed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserNotificationsRepository_MarkEmailAsFailed_Call) RunAndReturn(run func(ctx context.Context, id domain.UserNotificationID, reason string) error) *MockUserNotificationsRepository_MarkEmailAsFailed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkEmailAsSent provides a mock function for the type MockUserNotificationsRepository
func (_mock *MockUserNotificationsRepository) MarkEmailAsSent(ctx context.Context, id domain.UserNotificationID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkEmailAsSent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserNotificationID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserNotificationsRepository_MarkEmailAsSent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkEmailAsSent'
type MockUserNotificationsRepository_MarkEmailAsSent_Call struct {
	*mock.Call
}

// MarkEmailAsSent is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.UserNotificationID
func (_e *MockUserNotificationsRepository_Expecter) MarkEmailAsSent(ctx interface{}, id interface{}) *MockUserNotificationsRepository_MarkEmailAsSent_Call {
	return &MockUserNotificationsRepository_MarkEmailAsSent_Call{Call: _e.mock.On("MarkEmailAsSent", ctx, id)}
}

func (_c *MockUserNotificationsRepository_MarkEmailAsSent_Call) Run(run func(ctx context.Context, id domain.UserNotificationID)) *MockUserNotificationsRepository_MarkEmailAsSent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserNotificationID
		if args[1] != nil {
			arg1 = args[1].(domain.UserNotificationID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserNotificationsRepository_MarkEmailAsSent_Call) Return(err error) *MockUserNotificationsRepository_MarkEmailAsSent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserNotificationsRepository_MarkEmailAsSent_Call) RunAndReturn(run func(ctx context.Context, id domain.UserNotificationID) error) *MockUserNotificationsRepository_MarkEmailAsSent_Call {
	_c.Call.Return(run)
	return _c
}
