// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontract

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/togglr-project/togglr/internal/domain"
)

// NewMockFeatureContextualStatsRepository creates a new instance of MockFeatureContextualStatsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeatureContextualStatsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeatureContextualStatsRepository {
	mock := &MockFeatureContextualStatsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFeatureContextualStatsRepository is an autogenerated mock type for the FeatureContextualStatsRepository type
type MockFeatureContextualStatsRepository struct {
	mock.Mock
}

type MockFeatureContextualStatsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeatureContextualStatsRepository) EXPECT() *MockFeatureContextualStatsRepository_Expecter {
	return &MockFeatureContextualStatsRepository_Expecter{mock: &_m.Mock}
}

// InsertBatch provides a mock function for the type MockFeatureContextualStatsRepository
func (_mock *MockFeatureContextualStatsRepository) InsertBatch(ctx context.Context, records []domain.FeatureContextualStats) error {
	ret := _mock.Called(ctx, records)

	if len(ret) == 0 {
		panic("no return value specified for InsertBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.FeatureContextualStats) error); ok {
		r0 = returnFunc(ctx, records)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFeatureContextualStatsRepository_InsertBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertBatch'
type MockFeatureContextualStatsRepository_InsertBatch_Call struct {
	*mock.Call
}

// InsertBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - records []domain.FeatureContextualStats
func (_e *MockFeatureContextualStatsRepository_Expecter) InsertBatch(ctx interface{}, records interface{}) *MockFeatureContextualStatsRepository_InsertBatch_Call {
	return &MockFeatureContextualStatsRepository_InsertBatch_Call{Call: _e.mock.On("InsertBatch", ctx, records)}
}

func (_c *MockFeatureContextualStatsRepository_InsertBatch_Call) Run(run func(ctx context.Context, records []domain.FeatureContextualStats)) *MockFeatureContextualStatsRepository_InsertBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.FeatureContextualStats
		if args[1] != nil {
			arg1 = args[1].([]domain.FeatureContextualStats)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFeatureContextualStatsRepository_InsertBatch_Call) Return(err error) *MockFeatureContextualStatsRepository_InsertBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFeatureContextualStatsRepository_InsertBatch_Call) RunAndReturn(run func(ctx context.Context, records []domain.FeatureContextualStats) error) *MockFeatureContextualStatsRepository_InsertBatch_Call {
	_c.Call.Return(run)
	return _c
}

// LoadAll provides a mock function for the type MockFeatureContextualStatsRepository
func (_mock *MockFeatureContextualStatsRepository) LoadAll(ctx context.Context) ([]domain.FeatureContextualStats, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadAll")
	}

	var r0 []domain.FeatureContextualStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.FeatureContextualStats, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.FeatureContextualStats); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FeatureContextualStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeatureContextualStatsRepository_LoadAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadAll'
type MockFeatureContextualStatsRepository_LoadAll_Call struct {
	*mock.Call
}

// LoadAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFeatureContextualStatsRepository_Expecter) LoadAll(ctx interface{}) *MockFeatureContextualStatsRepository_LoadAll_Call {
	return &MockFeatureContextualStatsRepository_LoadAll_Call{Call: _e.mock.On("LoadAll", ctx)}
}

func (_c *MockFeatureContextualStatsRepository_LoadAll_Call) Run(run func(ctx context.Context)) *MockFeatureContextualStatsRepository_LoadAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFeatureContextualStatsRepository_LoadAll_Call) Return(featureContextualStatss []domain.FeatureContextualStats, err error) *MockFeatureContextualStatsRepository_LoadAll_Call {
	_c.Call.Return(featureContextualStatss, err)
	return _c
}

func (_c *MockFeatureContextualStatsRepository_LoadAll_Call) RunAndReturn(run func(ctx context.Context) ([]domain.FeatureContextualStats, error)) *MockFeatureContextualStatsRepository_LoadAll_Call {
	_c.Call.Return(run)
	return _c
}
